// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: magic_links.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeMagicLink = `-- name: ConsumeMagicLink :one
UPDATE magic_links
SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL
RETURNING id
`

func (q *Queries) ConsumeMagicLink(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, consumeMagicLink, id)
	err := row.Scan(&id)
	return id, err
}

const createOrUpdateMagicLinkToken = `-- name: CreateOrUpdateMagicLinkToken :one
INSERT INTO magic_links (user_id, token_hash, expires_at, consumed_at)
VALUES ($1, $2, $3, NULL)
ON CONFLICT (user_id) WHERE consumed_at IS NULL
DO UPDATE SET
	token_hash = EXCLUDED.token_hash,
	created_at = CURRENT_TIMESTAMP,
	expires_at = EXCLUDED.expires_at,
	consumed_at = NULL
RETURNING id, user_id, token_hash, expires_at, consumed_at, created_at
`

type CreateOrUpdateMagicLinkTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOrUpdateMagicLinkToken(ctx context.Context, arg CreateOrUpdateMagicLinkTokenParams) (MagicLink, error) {
	row := q.db.QueryRow(ctx, createOrUpdateMagicLinkToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findMagicLinkByTokenHash = `-- name: FindMagicLinkByTokenHash :one
SELECT
  ml.id,
  ml.user_id,
  ml.token_hash,
  ml.expires_at,
  ml.consumed_at,
  ml.created_at,
  u.email
FROM magic_links ml
JOIN users u ON u.id = ml.user_id
WHERE ml.token_hash = $1
  AND ml.consumed_at IS NULL
  AND ml.expires_at > now()
`

type FindMagicLinkByTokenHashRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Email      string             `json:"email"`
}

func (q *Queries) FindMagicLinkByTokenHash(ctx context.Context, tokenHash []byte) (FindMagicLinkByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, findMagicLinkByTokenHash, tokenHash)
	var i FindMagicLinkByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.Email,
	)
	return i, err
}
