root = "."
tmp_dir = "tmp"

[build]
cmd = "make -C .. generate && go build -o ./tmp/conjugate-api ./cmd/api"
bin = "./tmp/conjugate-api"
delay = 200
exclude_dir = ["bin", "tmp", "tools", "internal/api"]
include_ext = ["go", "yaml"]
