root = "."
tmp_dir = "tmp"

[build]
cmd = "HOST=${HOST:-localhost} PORT=${PORT:-8080} make -C .. build-dev"
bin = "./tmp/conjugate-api"
delay = 200
exclude_dir = ["bin", "tmp", "tools", "internal/api"]
include_ext = ["go", "yaml"]
