// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionCookieScopes = "sessionCookie.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// MagicLinkRequest defines model for MagicLinkRequest.
type MagicLinkRequest struct {
	Email openapi_types.Email `json:"email"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	BuildTime string `json:"build_time"`
	GitSha    string `json:"git_sha"`
}

// Status defines model for Status.
type Status struct {
	Status string `json:"status"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Code        string `json:"code"`
	FieldErrors []struct {
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"field_errors"`
	Message string `json:"message"`
}

// GetMagicLinkVerifyParams defines parameters for GetMagicLinkVerify.
type GetMagicLinkVerifyParams struct {
	// Token Magic link verification token
	Token string `form:"token" json:"token"`
}

// PostMagicLinkVerifyFormdataBody defines parameters for PostMagicLinkVerify.
type PostMagicLinkVerifyFormdataBody struct {
	Token string `form:"token" json:"token"`
}

// RequestMagicLinkJSONRequestBody defines body for RequestMagicLink for application/json ContentType.
type RequestMagicLinkJSONRequestBody = MagicLinkRequest

// PostMagicLinkVerifyFormdataRequestBody defines body for PostMagicLinkVerify for application/x-www-form-urlencoded ContentType.
type PostMagicLinkVerifyFormdataRequestBody PostMagicLinkVerifyFormdataBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Request magic link
	// (POST /v1/auth/magiclink/request)
	RequestMagicLink(w http.ResponseWriter, r *http.Request)
	// Verify magic link token (show confirmation page)
	// (GET /v1/auth/magiclink/verify)
	GetMagicLinkVerify(w http.ResponseWriter, r *http.Request, params GetMagicLinkVerifyParams)
	// Verify magic link token (create session)
	// (POST /v1/auth/magiclink/verify)
	PostMagicLinkVerify(w http.ResponseWriter, r *http.Request)
	// Logout (invalidate session)
	// (DELETE /v1/auth/session)
	DeleteSession(w http.ResponseWriter, r *http.Request)
	// Build metadata
	// (GET /v1/metadata)
	GetMetadata(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /v1/status)
	GetStatus(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Request magic link
// (POST /v1/auth/magiclink/request)
func (_ Unimplemented) RequestMagicLink(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify magic link token (show confirmation page)
// (GET /v1/auth/magiclink/verify)
func (_ Unimplemented) GetMagicLinkVerify(w http.ResponseWriter, r *http.Request, params GetMagicLinkVerifyParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify magic link token (create session)
// (POST /v1/auth/magiclink/verify)
func (_ Unimplemented) PostMagicLinkVerify(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout (invalidate session)
// (DELETE /v1/auth/session)
func (_ Unimplemented) DeleteSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Build metadata
// (GET /v1/metadata)
func (_ Unimplemented) GetMetadata(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /v1/status)
func (_ Unimplemented) GetStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RequestMagicLink operation middleware
func (siw *ServerInterfaceWrapper) RequestMagicLink(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestMagicLink(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMagicLinkVerify operation middleware
func (siw *ServerInterfaceWrapper) GetMagicLinkVerify(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMagicLinkVerifyParams

	// ------------- Required query parameter "token" -------------

	if paramValue := r.URL.Query().Get("token"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "token", r.URL.Query(), &params.Token)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMagicLinkVerify(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostMagicLinkVerify operation middleware
func (siw *ServerInterfaceWrapper) PostMagicLinkVerify(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostMagicLinkVerify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetMetadata(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetadata(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/magiclink/request", wrapper.RequestMagicLink)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/auth/magiclink/verify", wrapper.GetMagicLinkVerify)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/magiclink/verify", wrapper.PostMagicLinkVerify)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/auth/session", wrapper.DeleteSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/metadata", wrapper.GetMetadata)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/status", wrapper.GetStatus)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xXbU/kNhD+K5bbD3dS9v10VYOQenetCiq0iEX3oQghY89uzCZ2sCcL0Wn/e2XH2Ww2",
	"gaVvfIJ1ZjzPPPN4xv5Guc5yrUChpfE3ankCGfP//mKMNpdgc60suIXc6BwMSvCfuRZ+FZ5YlqdAYyrV",
	"mqVS3KJegaIRxTJ3yxaNVEu6iagAZDL13kwIiVIrll7s7IqmgK2fvrsHjs4vA2vZci/aVQIkN3otBQji",
	"QxJpScBAtCEJswSecmlAdMFsImrgofAf4+sqmSbQTQ+Ic7aU/Eyq1SU8FGCxywhkTKZtkIUF81P4OeQ6",
	"oxFdaJMxpHEwP4SssuoFBMgEQ9YFclfIVNyizPYom46nHwfj2WDy4WryQzybxbPxn311Wkq8tQlrO4vZ",
	"FD7+ODsIuHaOdmH04Z8jw8J20dvtehNcrw7GDW59kb46STAnN6/p12h5vXW5Be/TQ9NCQiqqz34XiZD1",
	"5OPN2rs/U/pnlJ4VFskdEEYqbXtvwoQwYO1BXqrwL2s7LDBjWPksjIZFsmAy/funao+xLpBNRC3wwkgs",
	"564PBT2AtVKrL1qvpIckFY0pr35GVLHMQ6isGkwsl79BSTduV6kW2nkKsNzI3OVAY/rp4pQstCGYAPmi",
	"1X2xZAhDzskazB3hYcXlK4xMU8LyPJXcrwxdHImel5brp4tTGtE1GFvFmAzHw7GjVOegWC5pTGfDyXBM",
	"I5ozTHyCo/VkxApMRplrMalUq5HZ6TG6+usk5WOfChrT0IS2TYlWzIPFz1qUlaYVgvKuO8BH99bhqhu9",
	"++97Awsa0+9GzSQYhTEw6jS9TbvGrmH7hWpK+HSm42mXa78RcbmRgJMwziFHEI6dD9Ppf4Z5/7R7yG00",
	"O1KGYBNRW2QZM2VDLsm2oL1BT53WYOTC072Enir9Ck2Fvlamru6GZYDgmsb1Czz5vQMFpJ6pXvsPBZiy",
	"kX79rV2WaIeu/WN60ynZeI9+hCccJZilbd73N+owe3J1fuaOzkK6KeeQ5+7ouxJ3YvzzErevJj0wzqW1",
	"Ui3DvWDLuMcxeUMcVz6+0kgWulAiIiw1wERJCgsicreU+obSVmAllh0Bhkze2UQ/dvl97xLrbxQX2vZo",
	"8HW94mnw+Pg4cBeWQWFSUK6fizY77VFXKbFHJ+25UJn19P+DvWXW11suQUgDHAlqkugMPCXkUWJCwlQg",
	"22mRABNQjeszXaXZTqiZd6Pe+TYHHDSjqM8vxDxmd3wynR2RC4bJ8eiInCDmf6i0PCJzN+TgiMxZBnOJ",
	"cHzGnnqCbfypmbydWk+ry3NUi9ILdFexoQ29UqvcAEOoa/C+3UPree2rmQJCV7o/+/X5drDvtawPXSUE",
	"2/oVwBAEsQXnYO2iSNOSvjWjv2skLl1Q6CLU5zxccnz/37veXN+47tywe6aXukDyrkmpS2i28xJ4dg7V",
	"Ngdb/7+4LdQxepiYg1lLDsQ/CkjWWO4m+7n70eXXvAieyy68Jf7H3EKEFzKTliTAUkzKvaxO/CrhCfCV",
	"P9Z/BQAA//+2R2PbdQ8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
