// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionCookieScopes = "sessionCookie.Scopes"
)

// Defines values for XRequestedWith.
const (
	XRequestedWithXMLHttpRequest XRequestedWith = "XMLHttpRequest"
)

// Defines values for RequestMagicLinkParamsXRequestedWith.
const (
	RequestMagicLinkParamsXRequestedWithXMLHttpRequest RequestMagicLinkParamsXRequestedWith = "XMLHttpRequest"
)

// Defines values for PostMagicLinkVerifyParamsXRequestedWith.
const (
	PostMagicLinkVerifyParamsXRequestedWithXMLHttpRequest PostMagicLinkVerifyParamsXRequestedWith = "XMLHttpRequest"
)

// Defines values for DeleteSessionParamsXRequestedWith.
const (
	DeleteSessionParamsXRequestedWithXMLHttpRequest DeleteSessionParamsXRequestedWith = "XMLHttpRequest"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// MagicLinkConfirmRequest defines model for MagicLinkConfirmRequest.
type MagicLinkConfirmRequest struct {
	Token string `json:"token"`
}

// MagicLinkConfirmResponse defines model for MagicLinkConfirmResponse.
type MagicLinkConfirmResponse struct {
	Email  openapi_types.Email `json:"email"`
	UserId openapi_types.UUID  `json:"user_id"`
}

// MagicLinkRequest defines model for MagicLinkRequest.
type MagicLinkRequest struct {
	Email openapi_types.Email `json:"email"`
}

// MagicLinkVerifyResponse defines model for MagicLinkVerifyResponse.
type MagicLinkVerifyResponse struct {
	Email openapi_types.Email `json:"email"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	BuildTime string `json:"build_time"`
	GitSha    string `json:"git_sha"`
}

// Status defines model for Status.
type Status struct {
	Status string `json:"status"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Code        string `json:"code"`
	FieldErrors []struct {
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"field_errors"`
	Message string `json:"message"`
}

// XRequestedWith defines model for XRequestedWith.
type XRequestedWith string

// RequestMagicLinkParams defines parameters for RequestMagicLink.
type RequestMagicLinkParams struct {
	XRequestedWith RequestMagicLinkParamsXRequestedWith `json:"X-Requested-With"`
}

// RequestMagicLinkParamsXRequestedWith defines parameters for RequestMagicLink.
type RequestMagicLinkParamsXRequestedWith string

// GetMagicLinkVerifyParams defines parameters for GetMagicLinkVerify.
type GetMagicLinkVerifyParams struct {
	// Token Magic link verification token
	Token string `form:"token" json:"token"`
}

// PostMagicLinkVerifyParams defines parameters for PostMagicLinkVerify.
type PostMagicLinkVerifyParams struct {
	XRequestedWith PostMagicLinkVerifyParamsXRequestedWith `json:"X-Requested-With"`
}

// PostMagicLinkVerifyParamsXRequestedWith defines parameters for PostMagicLinkVerify.
type PostMagicLinkVerifyParamsXRequestedWith string

// DeleteSessionParams defines parameters for DeleteSession.
type DeleteSessionParams struct {
	XRequestedWith DeleteSessionParamsXRequestedWith `json:"X-Requested-With"`
}

// DeleteSessionParamsXRequestedWith defines parameters for DeleteSession.
type DeleteSessionParamsXRequestedWith string

// RequestMagicLinkJSONRequestBody defines body for RequestMagicLink for application/json ContentType.
type RequestMagicLinkJSONRequestBody = MagicLinkRequest

// PostMagicLinkVerifyJSONRequestBody defines body for PostMagicLinkVerify for application/json ContentType.
type PostMagicLinkVerifyJSONRequestBody = MagicLinkConfirmRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Request magic link
	// (POST /v1/auth/magiclink/request)
	RequestMagicLink(w http.ResponseWriter, r *http.Request, params RequestMagicLinkParams)
	// Validate magic link token (read-only, does not consume)
	// (GET /v1/auth/magiclink/verify)
	GetMagicLinkVerify(w http.ResponseWriter, r *http.Request, params GetMagicLinkVerifyParams)
	// Confirm sign-in (consume token, create session)
	// (POST /v1/auth/magiclink/verify)
	PostMagicLinkVerify(w http.ResponseWriter, r *http.Request, params PostMagicLinkVerifyParams)
	// Logout (invalidate session)
	// (DELETE /v1/auth/session)
	DeleteSession(w http.ResponseWriter, r *http.Request, params DeleteSessionParams)
	// Build metadata
	// (GET /v1/metadata)
	GetMetadata(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /v1/status)
	GetStatus(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Request magic link
// (POST /v1/auth/magiclink/request)
func (_ Unimplemented) RequestMagicLink(w http.ResponseWriter, r *http.Request, params RequestMagicLinkParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Validate magic link token (read-only, does not consume)
// (GET /v1/auth/magiclink/verify)
func (_ Unimplemented) GetMagicLinkVerify(w http.ResponseWriter, r *http.Request, params GetMagicLinkVerifyParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Confirm sign-in (consume token, create session)
// (POST /v1/auth/magiclink/verify)
func (_ Unimplemented) PostMagicLinkVerify(w http.ResponseWriter, r *http.Request, params PostMagicLinkVerifyParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout (invalidate session)
// (DELETE /v1/auth/session)
func (_ Unimplemented) DeleteSession(w http.ResponseWriter, r *http.Request, params DeleteSessionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Build metadata
// (GET /v1/metadata)
func (_ Unimplemented) GetMetadata(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /v1/status)
func (_ Unimplemented) GetStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RequestMagicLink operation middleware
func (siw *ServerInterfaceWrapper) RequestMagicLink(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params RequestMagicLinkParams

	headers := r.Header

	// ------------- Required header parameter "X-Requested-With" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Requested-With")]; found {
		var XRequestedWith RequestMagicLinkParamsXRequestedWith
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Requested-With", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Requested-With", valueList[0], &XRequestedWith, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Requested-With", Err: err})
			return
		}

		params.XRequestedWith = XRequestedWith

	} else {
		err := fmt.Errorf("Header parameter X-Requested-With is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Requested-With", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestMagicLink(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMagicLinkVerify operation middleware
func (siw *ServerInterfaceWrapper) GetMagicLinkVerify(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMagicLinkVerifyParams

	// ------------- Required query parameter "token" -------------

	if paramValue := r.URL.Query().Get("token"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "token", r.URL.Query(), &params.Token)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMagicLinkVerify(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostMagicLinkVerify operation middleware
func (siw *ServerInterfaceWrapper) PostMagicLinkVerify(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostMagicLinkVerifyParams

	headers := r.Header

	// ------------- Required header parameter "X-Requested-With" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Requested-With")]; found {
		var XRequestedWith PostMagicLinkVerifyParamsXRequestedWith
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Requested-With", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Requested-With", valueList[0], &XRequestedWith, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Requested-With", Err: err})
			return
		}

		params.XRequestedWith = XRequestedWith

	} else {
		err := fmt.Errorf("Header parameter X-Requested-With is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Requested-With", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostMagicLinkVerify(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteSessionParams

	headers := r.Header

	// ------------- Required header parameter "X-Requested-With" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Requested-With")]; found {
		var XRequestedWith DeleteSessionParamsXRequestedWith
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Requested-With", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Requested-With", valueList[0], &XRequestedWith, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Requested-With", Err: err})
			return
		}

		params.XRequestedWith = XRequestedWith

	} else {
		err := fmt.Errorf("Header parameter X-Requested-With is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Requested-With", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSession(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetMetadata(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetadata(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/magiclink/request", wrapper.RequestMagicLink)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/auth/magiclink/verify", wrapper.GetMagicLinkVerify)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/magiclink/verify", wrapper.PostMagicLinkVerify)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/auth/session", wrapper.DeleteSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/metadata", wrapper.GetMetadata)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/status", wrapper.GetStatus)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXbW/bNhD+KwS3Dy0g2/JL0lVBgbXdsAZLt6DuumJBENDk2WItkSpJGRUK//eBFGW9",
	"us6ApNgnwxTv7rm3545fMZVpJgUIo3H0FWdEkRQMKPfv4zv4nIM2wP7mJrYnXOAIx0AYKBxgQVLAEf44",
	"OtwbuYsBVvA55woYjozKIcCaxpASqwFEnuLoBn98e/XGmMxL4tsAmyKz2rRRXGzwfr+vxByWX5WS6h3o",
	"TAoNDqqSGSjDwX2mkrlT+ELSLLF6uNiRhLM7I7cgcE99gBkYwhMnTRjjhktBkuuG1hK6l5OrT0CNlUtB",
	"a7LpWHsfA8qU3HEGDDmTiGvkMSCpUEw0gi+ZC0rf12bEbkpnakO3AyDekg2nV1xsX0ux5iqt4tgLTOl+",
	"CytZ0elszmC9ODs/iaWUvx+EY8mBlPCkjSHXoH72f8dUpjjAa6lSYnDkrw9kzArdcdbWdHYWwk+LMBzB",
	"7PlqtJiyxYg8m56PFovz87OzxSIMw7CpPc/56QxUlgIP5pv+H439w/jdgXYPQB9A8XXx2Pm4Py4whBFD",
	"+kBWOU/YneFpp5tm4ex8FM5H08X76bNoPo/m4T9DBbHh5k7HpC3M5jM4fz4/CbgSDpowhvAvDTG57qPX",
	"h/PauNyetOvFhix9sGxBLBM5ursPze0OInfgZAbCtOaQsPKz08INpAP+uGtt7UdbcZAE01wbtAJEUEl7",
	"ThoRxhRofTIupflv054/IEqR4iiMOopoTXjy3wm3E7E+EDuagOaKm2JpR5SvB9CaS/Fayi2Hw7Sk5d/D",
	"tPS3akwk479DUQ48LtbSSjLQVPHM+oAj/PL6Eq2lQiYG9FqKT/mGGBhTinagVoj6E+svUzxJEMmyhFN3",
	"MrZ2uHFxaYm+vL7EAd6B0qWN6TgchzakMgNBMo4jPB+H4ykOcEZM7Byc7KYTkpt4klqmSbjYTlSD+2T5",
	"a0vK2b5kOMKeHA/c5PTVS8bNV/yjgjWO8A+TehWZ1FcmnSVkf1umDrR5JVlRNoUwIJzthueTT1q6wVfv",
	"HkOW/Iox6bH5vl0kdhlwByWpunjMwlk/WU4RssFBHicilEJmgNnwLmazB8PcpQsHuY2m0Qvg7wRY52lK",
	"VFFnB6UH0O7CQKJ3bqZYRBsYSPNvYDrjp5/oo3Fyun0IULWvueb5nIMq6t6pvh1fL7t9fttLWfjwJdOZ",
	"twNpeF9thI4YL5ACkyuhEdFaUk4MVGRp25yW+1QZjr8uXdU8IOz2Jj0A9i3XmouNX2MPSXQ4pt8RRxk0",
	"IQ1ay1ywAJFEAWEFyjWwwC7V1ULdLmpf89Coau/LEys/kiIpAsQkaKecSqHzFJ5a/4Y57Frq09X9P6Ox",
	"zrvgXmwWPiKM42lelgMRUQWuEXROKWi9zpPEhrl8bTqESzCjero23pSH0e+H64vyiXOBromJX0wukH1q",
	"/imS4gIt7dyGC7QkKSy5gRdX5MvAfrB3TTf9fsV+WT4Vg6qmXX03C94TY7vUfXiR5hsx4gI98cVcXg58",
	"TJEPy9M2uVebiBthCRjoV/4v7nx5WFkeoOZbFbfoz8+qHPzbuV8S3zszf0iDbLxAGGuhohu//7k4dDa/",
	"m1vrap2lK7mRuUFPapf6GUkbj6SjE7a685idW9kY7FS14xSQey+htL7ZdPZV/6P1r34sHfPOP7Me0Tdv",
	"4RuecY1iIImJi45Xb9wpojHQraOHfwMAAP//FLmsbzoTAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
