// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionCookieScopes = "sessionCookie.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// MagicLinkConfirmRequest defines model for MagicLinkConfirmRequest.
type MagicLinkConfirmRequest struct {
	Token string `json:"token"`
}

// MagicLinkConfirmResponse defines model for MagicLinkConfirmResponse.
type MagicLinkConfirmResponse struct {
	Email  openapi_types.Email `json:"email"`
	UserId openapi_types.UUID  `json:"user_id"`
}

// MagicLinkRequest defines model for MagicLinkRequest.
type MagicLinkRequest struct {
	Email openapi_types.Email `json:"email"`
}

// MagicLinkVerifyResponse defines model for MagicLinkVerifyResponse.
type MagicLinkVerifyResponse struct {
	Email openapi_types.Email `json:"email"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	BuildTime string `json:"build_time"`
	GitSha    string `json:"git_sha"`
}

// Status defines model for Status.
type Status struct {
	Status string `json:"status"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Code        string `json:"code"`
	FieldErrors []struct {
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"field_errors"`
	Message string `json:"message"`
}

// GetMagicLinkVerifyParams defines parameters for GetMagicLinkVerify.
type GetMagicLinkVerifyParams struct {
	// Token Magic link verification token
	Token string `form:"token" json:"token"`
}

// RequestMagicLinkJSONRequestBody defines body for RequestMagicLink for application/json ContentType.
type RequestMagicLinkJSONRequestBody = MagicLinkRequest

// PostMagicLinkVerifyJSONRequestBody defines body for PostMagicLinkVerify for application/json ContentType.
type PostMagicLinkVerifyJSONRequestBody = MagicLinkConfirmRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Request magic link
	// (POST /v1/auth/magiclink/request)
	RequestMagicLink(w http.ResponseWriter, r *http.Request)
	// Validate magic link token (read-only, does not consume)
	// (GET /v1/auth/magiclink/verify)
	GetMagicLinkVerify(w http.ResponseWriter, r *http.Request, params GetMagicLinkVerifyParams)
	// Confirm sign-in (consume token, create session)
	// (POST /v1/auth/magiclink/verify)
	PostMagicLinkVerify(w http.ResponseWriter, r *http.Request)
	// Logout (invalidate session)
	// (DELETE /v1/auth/session)
	DeleteSession(w http.ResponseWriter, r *http.Request)
	// Build metadata
	// (GET /v1/metadata)
	GetMetadata(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /v1/status)
	GetStatus(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Request magic link
// (POST /v1/auth/magiclink/request)
func (_ Unimplemented) RequestMagicLink(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Validate magic link token (read-only, does not consume)
// (GET /v1/auth/magiclink/verify)
func (_ Unimplemented) GetMagicLinkVerify(w http.ResponseWriter, r *http.Request, params GetMagicLinkVerifyParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Confirm sign-in (consume token, create session)
// (POST /v1/auth/magiclink/verify)
func (_ Unimplemented) PostMagicLinkVerify(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout (invalidate session)
// (DELETE /v1/auth/session)
func (_ Unimplemented) DeleteSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Build metadata
// (GET /v1/metadata)
func (_ Unimplemented) GetMetadata(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /v1/status)
func (_ Unimplemented) GetStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RequestMagicLink operation middleware
func (siw *ServerInterfaceWrapper) RequestMagicLink(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestMagicLink(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMagicLinkVerify operation middleware
func (siw *ServerInterfaceWrapper) GetMagicLinkVerify(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMagicLinkVerifyParams

	// ------------- Required query parameter "token" -------------

	if paramValue := r.URL.Query().Get("token"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "token", r.URL.Query(), &params.Token)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMagicLinkVerify(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostMagicLinkVerify operation middleware
func (siw *ServerInterfaceWrapper) PostMagicLinkVerify(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostMagicLinkVerify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetMetadata(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetadata(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/magiclink/request", wrapper.RequestMagicLink)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/auth/magiclink/verify", wrapper.GetMagicLinkVerify)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/magiclink/verify", wrapper.PostMagicLinkVerify)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/auth/session", wrapper.DeleteSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/metadata", wrapper.GetMetadata)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/status", wrapper.GetStatus)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xXbW/bNhD+KwS3Dy0g2/JL3NVBgbXdsAZLt6DO+mFBENDk2WIskQpJGREK//eBFGW9",
	"OsmAJJ8SUzzec88dnzv+wFQmqRQgjMaLH1jTCBLi/v1dKam+gU6l0GAXUiVTUIaD+0wlc6twT5I0BrzA",
	"XOxIzNmNkVsQOMAmT+2yNoqLDd4HmIEhPHbWhDFuuBQkvqidalQGBzu5ugVqrF0CWpNNy9tlBChVcscZ",
	"MORcIq6Rx4CkQhHRCO5TroB1wewDrOAucx8XV0UwlaPrHhBfyYbTcy62n6VYc5V8g7sMtOkSU4TfwEpW",
	"dDyZMljPTuaPYinsnwbhWHIgITxuYsg0qF/9zyGVCQ7wWqqEGLzw23syZo1uOGuedHISwi+zMBzA5P1q",
	"MBuz2YC8G88Hs9l8fnIym4VhGNZPzzL+eAZKT4EH82D8R7l/nrhb0J4A6Dsovs5fOh9PxwWGMGJIF8gq",
	"4zG7MTxp3aZJOJkPwulgPLscv1tMp4tp+G9fQWy4udERaRqz6QTm76ePAi6NgzqMPvxLQ0ymu+j1Yb1y",
	"LreP+vVmfZ6+W7UgVomc3D1F5nYHkxtwNj00rTnErPjsTuEGkp543Lbm6UevYq8IJpk2aAWIoEL2nDUi",
	"jCnQ+lFeCvcPy55fIEqR/CiMikW0Jjz+/4LbYqwLZB9gDTRT3ORL26J8PYDWXIrPUm65g8QFXmBa/Ayw",
	"IImDUOyqMJGU/wk53ttTuVhLa8lAU8VTGwNe4I8XZ2gtFTIRoM9S3GYbYmBIKdqBWiHqV2y8TPE4RiRN",
	"Y07dytD64cbx0jD9eHGGA7wDpQsf42E4DC2lMgVBUo4XeDocD610psRELsDRbjwimYlGiVWamIvtSNW0",
	"TxZ/bUk532cML7AXx4M24YJ50OaTZHlR08KAcKY14KNbLUU1A9j/flawxgv806gaEkZ+Qhh1xHjfzLHt",
	"5W6h0EQXziScdLl2ByEbG/I4EaEUUgPMsjObTJ4Nc/u2O8hNNLVSBr8nwDpLEqLyilyUHEC7DT152rmW",
	"YBFtoCdLf4BpdQ+Xd0USMGBF4+oBntzZngJUjluu9u8yUHlV+uW3ZlqCGl3ta3rdSVn4/CXTapc9abgs",
	"Bzqna6dIgcmU0IhoLSknBkqts7eUFuNQQcc/Z65qnhF2cxDuAfuVa83Fxk+hhyQ6HONXxFGQJqRBa5kJ",
	"FiASKyAsR5kGFtiZuJyHm0Xtax5qVe1jeWPtB1LEeYCYBO0Op1LoLIG3Nr5+CbqQuqe6X1SFWlP5k8Qo",
	"fEEYx7O0LNoRogpcHeuMUtB6ncWxZSkCwqCYGpZgBlVvq5BUjde3tg/FA+MUXRATfRidoi/GpH+LOD9F",
	"S9s14RQtSQJLbuDDObnv6c57d2fGr1erZ8VDLShL0pVnvV69rjUr1dOLNN+IARfoja/FYnPgOUWelrdN",
	"bS7nANeBYjDQLdzf3PryMDC0CmbW7V5lNv3Ds5vR1yb2L2mQDReEsR7Ky+6HJ9dXWmPT1bVV/Yrkc7mR",
	"mUFvqpC6hCa1F8bR/lbuecmLV/rovWhqxykg99hASbWzHuyn7kcbX/XSOBadf6O8YGzewwORcY0iILGJ",
	"8lZUX9wqohHQrbvd/wUAAP//QeJyc+gRAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
